/* The following code was generated by JFlex 1.4.3 on 23/03/14 12.00 */

/*
 *  The scanner definition for COOL.
 */

import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 23/03/14 12.00 from the specification file
 * <tt>C:/Users/Mattia/git/LXR2014/cool.lex</tt>
 */
class CoolLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\2\1\1\1\0\1\2\1\7\22\0\1\2\1\0\1\74"+
    "\5\0\1\67\1\70\1\56\1\54\1\66\1\12\1\62\1\55\1\3"+
    "\11\4\1\65\1\64\1\57\1\60\1\73\1\0\1\63\1\25\1\10"+
    "\1\21\1\43\1\13\1\17\1\10\1\35\1\31\2\10\1\23\1\10"+
    "\1\33\1\15\1\46\1\10\1\37\1\27\1\41\1\52\1\45\1\50"+
    "\3\10\4\0\1\5\1\0\1\26\1\11\1\22\1\44\1\14\1\20"+
    "\1\11\1\36\1\32\2\11\1\24\1\11\1\34\1\16\1\47\1\11"+
    "\1\40\1\30\1\42\1\53\1\6\1\51\3\11\1\71\1\0\1\72"+
    "\1\61\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\6\1\5\1\6\1\5\1\6\1\5\1\6\1\5"+
    "\1\6\1\5\1\6\1\5\1\6\1\5\1\6\1\5"+
    "\1\6\1\5\1\6\1\5\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\2\3\1\0\2\6\2\5"+
    "\2\30\1\31\1\5\1\31\2\6\2\5\2\6\2\5"+
    "\1\32\1\33\1\6\1\32\1\33\1\5\2\6\2\5"+
    "\1\6\2\5\1\6\1\5\1\6\1\5\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\0\2\6\3\5"+
    "\2\6\2\5\1\43\1\6\1\43\1\5\2\6\2\5"+
    "\1\44\1\45\1\44\1\45\1\6\2\5\1\6\1\5"+
    "\1\6\1\5\1\0\1\46\1\47\1\46\1\47\1\5"+
    "\1\6\1\50\1\5\1\50\2\51\2\6\2\5\2\52"+
    "\1\53\2\54\1\6\1\5\1\2\1\55\2\56\2\6"+
    "\2\5\2\57\1\6\1\60\1\5\1\60\1\6\1\5"+
    "\2\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[160];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\172\0\267\0\267\0\267\0\364\0\u0131"+
    "\0\u016e\0\u01ab\0\u01e8\0\u0225\0\u0262\0\u029f\0\u02dc\0\u0319"+
    "\0\u0356\0\u0393\0\u03d0\0\u040d\0\u044a\0\u0487\0\u04c4\0\u0501"+
    "\0\u053e\0\u057b\0\u05b8\0\u05f5\0\u0632\0\u066f\0\267\0\267"+
    "\0\u06ac\0\u06e9\0\u0726\0\267\0\267\0\267\0\267\0\267"+
    "\0\267\0\u0763\0\267\0\267\0\267\0\267\0\u07a0\0\u07dd"+
    "\0\u081a\0\u0857\0\u0894\0\u08d1\0\u090e\0\u016e\0\u0131\0\u016e"+
    "\0\u094b\0\u0131\0\u0988\0\u09c5\0\u0a02\0\u0a3f\0\u0a7c\0\u0ab9"+
    "\0\u0af6\0\u0b33\0\u016e\0\u0b70\0\u0bad\0\u0131\0\u0bea\0\u0c27"+
    "\0\u0c64\0\u0ca1\0\u0cde\0\u0d1b\0\u0d58\0\u0d95\0\u0dd2\0\u0e0f"+
    "\0\u0e4c\0\u0e89\0\u0ec6\0\267\0\267\0\267\0\267\0\267"+
    "\0\267\0\267\0\u0f03\0\u0f40\0\u0f7d\0\u0fba\0\u0ff7\0\u1034"+
    "\0\u1071\0\u10ae\0\u10eb\0\u1128\0\u016e\0\u1165\0\u0131\0\u11a2"+
    "\0\u11df\0\u121c\0\u1259\0\u1296\0\u016e\0\u016e\0\u0131\0\u0131"+
    "\0\u12d3\0\u1310\0\u134d\0\u138a\0\u13c7\0\u1404\0\u1441\0\u147e"+
    "\0\u016e\0\u016e\0\u0131\0\u0131\0\u14bb\0\u14f8\0\u016e\0\u1535"+
    "\0\u0131\0\u016e\0\u0131\0\u1572\0\u15af\0\u15ec\0\u1629\0\u016e"+
    "\0\u0131\0\u0131\0\u016e\0\u0131\0\u1666\0\u16a3\0\u081a\0\u0131"+
    "\0\u016e\0\u0131\0\u16e0\0\u171d\0\u175a\0\u1797\0\u016e\0\u0131"+
    "\0\u17d4\0\u016e\0\u1811\0\u0131\0\u184e\0\u188b\0\u016e\0\u0131";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[160];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\4\1\7\1\4\1\10\1\6"+
    "\1\11\1\10\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\11\1\10\1\11"+
    "\1\10\1\25\1\26\1\27\1\30\1\11\1\10\1\11"+
    "\1\10\1\31\1\32\1\11\1\10\1\11\1\33\1\34"+
    "\1\35\1\36\1\11\1\10\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\4\1\56\1\4\1\0\73\4"+
    "\1\6\1\5\54\6\1\57\10\6\1\60\5\6\100\0"+
    "\2\7\73\0\4\10\1\0\2\10\1\0\41\10\24\0"+
    "\4\11\1\0\2\11\1\0\41\11\33\0\1\61\65\0"+
    "\4\11\1\0\2\11\1\0\10\11\2\62\2\11\2\63"+
    "\23\11\24\0\4\10\1\0\2\10\1\0\10\10\2\64"+
    "\2\10\2\65\23\10\24\0\4\11\1\0\2\11\1\0"+
    "\4\11\2\66\33\11\24\0\4\10\1\0\2\10\1\0"+
    "\4\10\2\67\33\10\24\0\4\11\1\0\2\11\1\0"+
    "\16\11\2\70\21\11\24\0\4\10\1\0\2\10\1\0"+
    "\12\10\2\71\2\10\2\72\21\10\24\0\4\11\1\0"+
    "\2\11\1\0\10\11\2\73\2\74\25\11\24\0\4\10"+
    "\1\0\2\10\1\0\10\10\2\75\2\76\25\10\24\0"+
    "\4\11\1\0\2\11\1\0\2\77\2\100\35\11\24\0"+
    "\4\10\1\0\2\10\1\0\2\101\2\102\35\10\24\0"+
    "\4\11\1\0\2\11\1\0\4\11\2\103\12\11\2\104"+
    "\6\11\2\105\7\11\24\0\4\10\1\0\2\10\1\0"+
    "\4\10\2\106\12\10\2\107\6\10\2\110\7\10\24\0"+
    "\4\11\1\0\2\11\1\0\2\111\2\112\35\11\24\0"+
    "\4\10\1\0\2\10\1\0\2\113\2\114\35\10\24\0"+
    "\4\11\1\0\2\11\1\0\22\11\2\115\15\11\24\0"+
    "\4\10\1\0\2\10\1\0\22\10\2\116\2\117\13\10"+
    "\24\0\4\11\1\0\2\11\1\0\2\11\2\120\35\11"+
    "\24\0\4\10\1\0\2\10\1\0\2\10\2\121\35\10"+
    "\24\0\4\11\1\0\2\11\1\0\22\11\2\122\15\11"+
    "\24\0\4\10\1\0\2\10\1\0\22\10\2\123\15\10"+
    "\111\0\1\124\16\0\1\125\45\0\1\126\107\0\1\127"+
    "\57\0\1\130\106\0\1\131\62\0\1\132\16\0\1\61"+
    "\1\5\5\61\1\0\3\61\2\133\60\61\3\0\4\11"+
    "\1\0\2\11\1\0\14\11\2\134\23\11\24\0\4\11"+
    "\1\0\2\11\1\0\12\11\2\135\25\11\24\0\4\10"+
    "\1\0\2\10\1\0\14\10\2\136\23\10\24\0\4\10"+
    "\1\0\2\10\1\0\12\10\2\137\25\10\24\0\4\10"+
    "\1\0\2\10\1\0\10\10\2\140\27\10\24\0\4\11"+
    "\1\0\2\11\1\0\12\11\2\141\25\11\24\0\4\11"+
    "\1\0\2\11\1\0\14\11\2\142\23\11\24\0\4\10"+
    "\1\0\2\10\1\0\12\10\2\143\25\10\24\0\4\10"+
    "\1\0\2\10\1\0\14\10\2\144\23\10\24\0\4\11"+
    "\1\0\2\11\1\0\26\11\2\145\11\11\24\0\4\11"+
    "\1\0\2\11\1\0\2\11\2\146\35\11\24\0\4\10"+
    "\1\0\2\10\1\0\26\10\2\147\11\10\24\0\4\10"+
    "\1\0\2\10\1\0\2\10\2\150\35\10\24\0\4\11"+
    "\1\0\2\11\1\0\22\11\2\151\15\11\24\0\3\11"+
    "\1\152\1\0\2\11\1\0\32\11\1\152\6\11\24\0"+
    "\4\10\1\0\2\10\1\0\22\10\2\153\15\10\24\0"+
    "\3\10\1\154\1\0\2\10\1\0\32\10\1\154\6\10"+
    "\24\0\4\11\1\0\2\11\1\0\35\11\2\155\2\11"+
    "\24\0\4\11\1\0\2\11\1\0\26\11\2\156\11\11"+
    "\24\0\4\10\1\0\2\10\1\0\35\10\2\157\2\10"+
    "\24\0\4\10\1\0\2\10\1\0\26\10\2\160\11\10"+
    "\24\0\4\11\1\0\2\11\1\0\2\161\37\11\24\0"+
    "\4\10\1\0\2\10\1\0\2\162\37\10\24\0\4\10"+
    "\1\0\2\10\1\0\37\10\2\163\24\0\4\11\1\0"+
    "\2\11\1\0\2\11\2\164\35\11\24\0\4\10\1\0"+
    "\2\10\1\0\2\10\2\165\35\10\24\0\4\11\1\0"+
    "\2\11\1\0\16\11\2\166\21\11\24\0\4\10\1\0"+
    "\2\10\1\0\16\10\2\167\21\10\21\0\1\61\1\5"+
    "\5\61\1\0\3\61\2\133\2\170\56\61\3\0\4\11"+
    "\1\0\2\11\1\0\2\171\37\11\24\0\4\11\1\0"+
    "\2\11\1\0\6\11\2\172\31\11\24\0\4\10\1\0"+
    "\2\10\1\0\2\173\37\10\24\0\4\10\1\0\2\10"+
    "\1\0\6\10\2\174\31\10\24\0\4\10\1\0\2\10"+
    "\1\0\14\10\2\175\23\10\24\0\4\11\1\0\2\11"+
    "\1\0\14\11\2\176\23\11\24\0\4\11\1\0\2\11"+
    "\1\0\2\177\37\11\24\0\4\10\1\0\2\10\1\0"+
    "\14\10\2\200\23\10\24\0\4\10\1\0\2\10\1\0"+
    "\2\201\37\10\24\0\4\11\1\0\2\11\1\0\33\11"+
    "\2\202\4\11\24\0\4\10\1\0\2\10\1\0\33\10"+
    "\2\203\4\10\24\0\4\11\1\0\2\11\1\0\2\204"+
    "\37\11\24\0\4\11\1\0\2\11\1\0\2\11\2\205"+
    "\35\11\24\0\4\10\1\0\2\10\1\0\2\206\37\10"+
    "\24\0\4\10\1\0\2\10\1\0\2\10\2\207\35\10"+
    "\24\0\4\11\1\0\2\11\1\0\20\11\2\210\17\11"+
    "\24\0\4\10\1\0\2\10\1\0\20\10\2\211\17\10"+
    "\24\0\4\10\1\0\2\10\1\0\2\212\37\10\24\0"+
    "\4\11\1\0\2\11\1\0\10\11\2\213\27\11\24\0"+
    "\4\10\1\0\2\10\1\0\10\10\2\214\27\10\24\0"+
    "\4\11\1\0\2\11\1\0\10\11\2\215\27\11\24\0"+
    "\4\10\1\0\2\10\1\0\10\10\2\216\27\10\21\0"+
    "\1\61\1\5\5\61\1\0\3\61\2\133\2\61\2\217"+
    "\54\61\3\0\4\10\1\0\2\10\1\0\2\220\37\10"+
    "\24\0\4\11\1\0\2\11\1\0\14\11\2\221\23\11"+
    "\24\0\4\10\1\0\2\10\1\0\14\10\2\222\23\10"+
    "\24\0\4\11\1\0\2\11\1\0\24\11\2\223\13\11"+
    "\24\0\4\11\1\0\2\11\1\0\16\11\2\224\21\11"+
    "\24\0\4\10\1\0\2\10\1\0\24\10\2\225\13\10"+
    "\24\0\4\10\1\0\2\10\1\0\16\10\2\226\21\10"+
    "\24\0\4\11\1\0\2\11\1\0\2\227\37\11\24\0"+
    "\4\10\1\0\2\10\1\0\2\230\37\10\24\0\4\11"+
    "\1\0\2\11\1\0\16\11\2\231\21\11\24\0\4\11"+
    "\1\0\2\11\1\0\30\11\2\232\7\11\24\0\4\10"+
    "\1\0\2\10\1\0\16\10\2\233\21\10\24\0\4\10"+
    "\1\0\2\10\1\0\30\10\2\234\7\10\24\0\4\11"+
    "\1\0\2\11\1\0\26\11\2\235\11\11\24\0\4\10"+
    "\1\0\2\10\1\0\26\10\2\236\11\10\24\0\4\11"+
    "\1\0\2\11\1\0\14\11\2\237\23\11\24\0\4\10"+
    "\1\0\2\10\1\0\14\10\2\240\23\10\21\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6344];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\3\11\30\1\2\11\3\1\6\11\1\1\4\11"+
    "\2\1\1\0\42\1\7\11\1\0\34\1\1\0\50\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[160];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

/*  Stuff enclosed in %{ %} is copied verbatim to the lexer class
 *  definition, all the extra variables/functions you want to use in the
 *  lexer actions should go here.  Don't remove or modify anything that
 *  was there initially.  */

    //our variables
    private int open_comments = 0;
    
    // Max size of string constants
    static int MAX_STR_CONST = 1025;

    // For assembling string constants
    StringBuffer string_buf = new StringBuffer();

    private int curr_lineno = 1;
    int get_curr_lineno() {
		return curr_lineno;
    //	return yyline;
    }

    //int get_curr_column() {
    //	return yycolumn;
    //}
    
    private AbstractSymbol filename;

    void set_filename(String fname) {
	filename = AbstractTable.stringtable.addString(fname);
    }
    
    /*
    AbstractSymbol set_number_in_filename(String fname) {
    filename = AbstractTable.inttable.addString(fname);
    return filename;
    }
    */
    
    /*
    AbstractSymbol set_identifier_in_filename(String fname) {
    filename = AbstractTable.idtable.addString(fname);
    return filename;
    }
    */
    

    AbstractSymbol curr_filename() {
	return filename;
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  CoolLexer(java.io.Reader in) {
  
/*  Stuff enclosed in %init{ %init} is copied verbatim to the lexer
 *  class constructor, all the extra initialization you want to do should
 *  go here.  Don't remove or modify anything that was there initially. */

    // empty for now
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  CoolLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 164) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 21: 
          { return new Symbol(TokenConstants.LBRACE);
          }
        case 50: break;
        case 45: 
          { return new Symbol(TokenConstants.BOOL_CONST, false);
          }
        case 51: break;
        case 33: 
          { open_comments--;
						if(open_comments==0)
						yybegin(YYINITIAL);
          }
        case 52: break;
        case 29: 
          { return new Symbol(TokenConstants.ASSIGN);
          }
        case 53: break;
        case 13: 
          { return new Symbol(TokenConstants.NEG);
          }
        case 54: break;
        case 26: 
          { return new Symbol(TokenConstants.IF);
          }
        case 55: break;
        case 35: 
          { return new Symbol(TokenConstants.LET);
          }
        case 56: break;
        case 3: 
          { /* ignore this */
          }
        case 57: break;
        case 34: 
          { open_comments++;
          }
        case 58: break;
        case 27: 
          { return new Symbol(TokenConstants.IN);
          }
        case 59: break;
        case 12: 
          { return new Symbol(TokenConstants.EQ);
          }
        case 60: break;
        case 15: 
          { return new Symbol(TokenConstants.AT);
          }
        case 61: break;
        case 36: 
          { return new Symbol(TokenConstants.NEW);
          }
        case 62: break;
        case 41: 
          { return new Symbol(TokenConstants.LOOP);
          }
        case 63: break;
        case 17: 
          { return new Symbol(TokenConstants.COLON);
          }
        case 64: break;
        case 8: 
          { return new Symbol(TokenConstants.PLUS);
          }
        case 65: break;
        case 39: 
          { return new Symbol(TokenConstants.ESAC);
          }
        case 66: break;
        case 19: 
          { return new Symbol(TokenConstants.LPAREN);
          }
        case 67: break;
        case 47: 
          { return new Symbol(TokenConstants.WHILE);
          }
        case 68: break;
        case 32: 
          { yybegin(COMMENT);
          }
        case 69: break;
        case 40: 
          { return new Symbol(TokenConstants.CASE);
          }
        case 70: break;
        case 43: 
          { return new Symbol(TokenConstants.BOOL_CONST, true);
          }
        case 71: break;
        case 49: 
          { return new Symbol(TokenConstants.INHERITS);
          }
        case 72: break;
        case 38: 
          { return new Symbol(TokenConstants.ELSE);
          }
        case 73: break;
        case 22: 
          { return new Symbol(TokenConstants.RBRACE);
          }
        case 74: break;
        case 14: 
          { return new Symbol(TokenConstants.DOT);
          }
        case 75: break;
        case 42: 
          { return new Symbol(TokenConstants.THEN);
          }
        case 76: break;
        case 30: 
          { return new Symbol(TokenConstants.LE);
          }
        case 77: break;
        case 10: 
          { return new Symbol(TokenConstants.MULT);
          }
        case 78: break;
        case 1: 
          { /* This rule should be the very last
						in your lexical specification and
						will match match everything not
						matched by other lexical rules. */
						System.err.println("LEXER BUG - UNMATCHED: " + yytext());
          }
        case 79: break;
        case 31: 
          { return new Symbol(TokenConstants.DARROW);
          }
        case 80: break;
        case 2: 
          { curr_lineno++;
          }
        case 81: break;
        case 25: 
          { return new Symbol(TokenConstants.FI);
          }
        case 82: break;
        case 6: 
          { return new Symbol(TokenConstants.TYPEID,AbstractTable.idtable.addString(yytext()));
          }
        case 83: break;
        case 7: 
          { return new Symbol(TokenConstants.MINUS);
          }
        case 84: break;
        case 23: 
          { yybegin(STRING);
          }
        case 85: break;
        case 28: 
          { return new Symbol(TokenConstants.ERROR,"Unmatched *)");
          }
        case 86: break;
        case 48: 
          { return new Symbol(TokenConstants.ISVOID);
          }
        case 87: break;
        case 24: 
          { return new Symbol(TokenConstants.OF);
          }
        case 88: break;
        case 16: 
          { return new Symbol(TokenConstants.SEMI);
          }
        case 89: break;
        case 37: 
          { return new Symbol(TokenConstants.NOT);
          }
        case 90: break;
        case 18: 
          { return new Symbol(TokenConstants.COMMA);
          }
        case 91: break;
        case 9: 
          { return new Symbol(TokenConstants.DIV);
          }
        case 92: break;
        case 11: 
          { return new Symbol(TokenConstants.LT);
          }
        case 93: break;
        case 5: 
          { return new Symbol(TokenConstants.OBJECTID,AbstractTable.idtable.addString(yytext()));
          }
        case 94: break;
        case 46: 
          { return new Symbol(TokenConstants.CLASS);
          }
        case 95: break;
        case 44: 
          { return new Symbol(TokenConstants.POOL);
          }
        case 96: break;
        case 20: 
          { return new Symbol(TokenConstants.RPAREN);
          }
        case 97: break;
        case 4: 
          { return new Symbol(TokenConstants.INT_CONST,AbstractTable.inttable.addString(yytext()));
          }
        case 98: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { 
/*  Stuff enclosed in %eofval{ %eofval} specifies java code that is
 *  executed when end-of-file is reached.  If you use multiple lexical
 *  states and want to do something special if an EOF is encountered in
 *  one of those states, place your code in the switch statement.
 *  Ultimately, you should return the EOF symbol, or your lexer won't
 *  work.  */

    switch(yystate()) {
    case YYINITIAL:
		/* nothing special to do in the initial state */
	break;
	case COMMENT:
		return new Symbol(TokenConstants.ERROR, "EOF in comment"); 
	//break;
	case STRING:
		
	break;
	}
    return new Symbol(TokenConstants.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
